### ISSUE TITLE
DB is unresponsive.

### ISSUE THREAD

**Issue by Neruelin** [Neruelin/cop4331-9#1]
Used heroku's guide to connecting to heroku's DB from Node.
Wrote a simple query to dump DB and send results to webclient.
Results of DB dump were "Internal Server Error."
DB code is isolated to server.js.
[Guide used.](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js)

**Comment by uulltt** [comment]
fixed it
